server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: sandbox
  datasource:
    url: jdbc:postgresql://localhost:5432/street-tournament?serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    user: postgres
    password: admin
    schemas: street-tournament
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/street-tournament?serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.SQL: DEBUG
